---
train:
  params:
    batch_size: 256
    epoch: 100
    lr: 0.0001
    decay: 0.1
    decay_step: 5000
    loss: MSELoss
  save:
    save_path: "./checkpoint/ECA"
    model_name: GazeNet
    step: 10
  data:
    image: "./dataset/EyeBased/MPIIGaze-new/Image"
    label: "./dataset/EyeBased/MPIIGaze-new/Label"
  pretrains: "None"
test:
   load:
      begin_step: 100
      end_step: 100
      steps: 10
      load_path: "./checkpoint/ECA"
      model_name: GazeNet
   data:
      image: "./dataset/EyeBased/MPIIGaze-new/Image"
      label: "./dataset/EyeBased/MPIIGaze-new/Label"
